version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    webserver:
        image: puckel/docker-airflow:1.8.1
        restart: always
        depends_on:
            - redis
        environment:
            - LOAD_EX=y
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=${EXECUTOR}
            - POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_QUEUE=${REDIS_QUEUE}
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: puckel/docker-airflow:1.8.1
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=${EXECUTOR}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_QUEUE=${REDIS_QUEUE}
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.8.1
        restart: always
        depends_on:
            - webserver
        environment:
            - LOAD_EX=y
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=${EXECUTOR}
            - POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_QUEUE=${REDIS_QUEUE}
        command: scheduler

    worker:
        image: puckel/docker-airflow:1.8.1
        restart: always
        depends_on:
            - scheduler
        environment:
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=${EXECUTOR}
            - POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_QUEUE=${REDIS_QUEUE}
        command: worker
